<a href="https://colab.research.google.com/github/junaidkhan035/JuniaidKhanProjects/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('/content/drive/MyDrive/data.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
349        11.95         14.96           77.23      426.7          0.11580   
112        14.26         19.65           97.83      629.9          0.07837   
275        11.89         17.36           76.20      435.6          0.12250   
73         13.80         15.79           90.43      584.1          0.10070   
457        13.21         25.25           84.10      537.9          0.08791   
..           ...           ...             ...        ...              ...   
241        12.42         15.04           78.61      476.5          0.07926   
522        11.26         19.83           71.30      388.1          0.08511   
259        15.53         33.56          103.70      744.9          0.10630   
263        15.61         19.38          100.00      758.6          0.07840   
124        13.37         16.39           86.10      553.5          0.07115   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
349           0.12060        0.011710             0.017870         0.2459   
112           0.22330        0.300300             0.077980         0.1704   
275           0.07210        0.059290             0.074040         0.2015   
73            0.12800        0.077890             0.050690         0.1662   
457           0.05205        0.027720             0.020680         0.1619   
..                ...             ...                  ...            ...   
241           0.03393        0.010530             0.011080         0.1546   
522           0.04413        0.005067             0.005664         0.1637   
259           0.16390        0.175100             0.083990         0.2091   
263           0.05616        0.042090             0.028470         0.1547   
124           0.07325        0.080920             0.028000         0.1422   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
349                 0.06581  ...         12.81          17.72   
112                 0.07769  ...         15.30          23.73   
275                 0.05875  ...         12.40          18.99   
73                  0.06566  ...         16.57          20.86   
457                 0.05584  ...         14.35          34.23   
..                      ...  ...           ...            ...   
241                 0.05754  ...         13.20          20.37   
522                 0.06343  ...         11.93          26.43   
259                 0.06650  ...         18.49          49.54   
263                 0.05443  ...         17.91          31.67   
124                 0.05823  ...         14.26          22.75   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
349            83.09       496.2           0.12930            0.18850   
112           107.00       709.0           0.08949            0.41930   
275            79.46       472.4           0.13590            0.08368   
73            110.30       812.4           0.14110            0.35420   
457            91.29       632.9           0.12890            0.10630   
..               ...         ...               ...                ...   
241            83.85       543.4           0.10370            0.07776   
522            76.38       435.9           0.11080            0.07723   
259           126.30      1035.0           0.18830            0.55640   
263           115.90       988.6           0.10840            0.18070   
124            91.99       632.1           0.10250            0.25310   

     concavity_worst  concave points_worst  symmetry_worst  \
349          0.03122               0.04766          0.3124   
112          0.67830               0.15050          0.2398   
275          0.07153               0.08946          0.2220   
73           0.27790               0.13830          0.2589   
457          0.13900               0.06005          0.2444   
..               ...                   ...             ...   
241          0.06243               0.04052         

# Scaling

In [9]:

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
x_train

array([[-0.60752624, -1.00676736, -0.5973366 , ..., -1.01955304,
         0.32487558, -0.46056177],
       [ 0.05918893,  0.07200223,  0.2639393 , ...,  0.54205605,
        -0.80585123,  1.25546975],
       [-0.62484351, -0.45473175, -0.6404004 , ..., -0.38482667,
        -1.08308177, -1.28776334],
       ...,
       [ 0.42573796,  3.27150861,  0.50936112, ...,  1.31496448,
         0.92917586,  1.90363026],
       [ 0.44882767,  0.00989822,  0.35466594, ..., -0.44222537,
        -0.36197087, -0.86486517],
       [-0.19768401, -0.67784614, -0.22648625, ..., -0.37996752,
        -1.35096747, -0.44037317]])

In [11]:
x_test

array([[-0.03316988, -1.41849392, -0.05046821, ..., -0.20200117,
        -1.17653027, -0.63960283],
       [ 0.63065907, -0.13041083,  0.72258963, ...,  0.88675195,
        -0.22647055,  1.15452672],
       [-0.73740582, -0.20401558, -0.76248417, ..., -0.74956656,
        -0.2731948 , -1.04656263],
       ...,
       [-0.56423304, -0.37192641, -0.56221662, ..., -0.79178041,
         0.20806496, -0.73098284],
       [-1.24480203, -0.84345682, -1.2550002 , ..., -0.95987661,
        -0.11588983, -0.14976349],
       [-0.24386342,  2.00642701, -0.27749385, ..., -0.5348529 ,
        -0.68904061, -1.06993891]])

In [12]:
y_train

349    B
112    B
275    B
73     M
457    B
      ..
241    B
522    B
259    M
263    M
124    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoder

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_test

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0])

In [15]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,

# Numpy arrays to pytorch tensor

In [16]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
x_train_tensor.shape

torch.Size([455, 30])

In [18]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [19]:
class MySimpleNN():



  def __init__(self, x):

    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [20]:
learning_rate = 0.1
epochs = 25

In [24]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(x_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.194225174868486
Epoch: 2, Loss: 4.091504646570789
Epoch: 3, Loss: 3.9827758782570815
Epoch: 4, Loss: 3.870428531046417
Epoch: 5, Loss: 3.7563778051738037
Epoch: 6, Loss: 3.640982846597318
Epoch: 7, Loss: 3.5219741141852943
Epoch: 8, Loss: 3.394789816024215
Epoch: 9, Loss: 3.260618680948883
Epoch: 10, Loss: 3.1206298299666706
Epoch: 11, Loss: 2.978945825622978
Epoch: 12, Loss: 2.833097866916066
Epoch: 13, Loss: 2.68446737481622
Epoch: 14, Loss: 2.5310267048134003
Epoch: 15, Loss: 2.376443649017743
Epoch: 16, Loss: 2.2223421222829236
Epoch: 17, Loss: 2.0685613242576437
Epoch: 18, Loss: 1.9143371538510188
Epoch: 19, Loss: 1.7629898147207856
Epoch: 20, Loss: 1.6188267583701206
Epoch: 21, Loss: 1.4857234899367595
Epoch: 22, Loss: 1.3645514245766635
Epoch: 23, Loss: 1.252291907340359
Epoch: 24, Loss: 1.1532711170385392
Epoch: 25, Loss: 1.0703600492786551


In [25]:
model.bias

tensor([-0.0745], dtype=torch.float64, requires_grad=True)

# Evaluation

In [26]:
# Model Evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6083410382270813
